language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: IJXoBjx7WD7/fQDJbZs4P2NNkrhpzOVAc7AWaV+ScrX4pxgX6hNEL7sTvjWASE4BsPxMgt1FB2iKje67CxjaoEI1wT0oPugLKhkv7OvvexJm2gW9rFwuHZHSdBL2m0RpV+jQp/cigt/0gTLewRIG22h0qPvFp/7j9T8CJ5iXGfEt94Qh1NcS3/zZX5kcmiXsL80Esx7owJnPpIvQtU0X5bSIsoq2zutl7+qX7M3tLRF6L6lW7953DH6Dbn1z7We39iZpIsDmRqMNP0jrx4uZ2OhtPVsZ3pAdvgE84/3T3q2JZIwX10N+Lut7KBSlayBI1RwkwHcc/4bHPB+2tae3yzUPfYSPBRDhyYMwCSNCjJd3JGni+YYVKOnrOD3a0PxkXmZEB+rwQ+lnGDh9zEfaVodoIOi1BzZCBjjam5DS/HHXrN1Pi6YzOQX2xUcIGj28N3kcK/cI19IP02wWUexlW5wfLTUpp2JxH0JLQgJeZHQyTA/1Jf/m+0XPwZOqw7pp6LjzCxAITkTeaTHk31rkQeQLE5xyVoeFSb2biarMzts7eLLzEW4YPKKuoCmyjz2tnMJRciEnP+s85+iiDOoC9T4Lkvg0PW3P1ZspO8SQR1PDWaNy4v5rLGzOfBDai1U9K4IrGlLjXwYUdRBjTaCC7YQq3Py2QUxz7SfgMcuUgRs=
  app: dollin-skeleton-java-app

